/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Admin
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    private JPanel sidebarPanel, contentPanel;

    public AdminForm() {
        setTitle("NgolDrinks - Admin");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 650);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Sidebar menu
        sidebarPanel = new JPanel();
        sidebarPanel.setLayout(new GridLayout(6, 1, 5, 5)); // 5 menu + 1 nút đăng xuất
        sidebarPanel.setBackground(new Color(34, 40, 49)); // Màu nền sidebar

        JButton btnTaiKhoan = new JButton("Quản lý tài khoản");
        JButton btnDoUong = new JButton("Quản lý đồ uống");
        JButton btnQuanLyDon = new JButton("Quản lý đơn");
        JButton btnKhuyenMai = new JButton("Quản lý khuyến mãi");
        JButton btnBan = new JButton("Quản lý bàn");
        JButton btnDangXuat = new JButton("Đăng xuất"); // 🔥 Nút đăng xuất

        styleButton(btnTaiKhoan);
        styleButton(btnDoUong);
        styleButton(btnQuanLyDon);
        styleButton(btnKhuyenMai);
        styleButton(btnBan);
        styleButton(btnDangXuat);

        sidebarPanel.add(btnTaiKhoan);
        sidebarPanel.add(btnDoUong);
        sidebarPanel.add(btnQuanLyDon);
        sidebarPanel.add(btnKhuyenMai);
        sidebarPanel.add(btnBan);
        sidebarPanel.add(btnDangXuat); // Thêm nút đăng xuất vào cuối

        // Content panel
        contentPanel = new JPanel(new BorderLayout());
        contentPanel.setBackground(Color.WHITE);

        add(sidebarPanel, BorderLayout.WEST);
        add(contentPanel, BorderLayout.CENTER);

        // Default show panel
        showPanel(new TaiKhoanPanel());

        // Menu button actions
        btnTaiKhoan.addActionListener(e -> showPanel(new TaiKhoanPanel()));
        btnDoUong.addActionListener(e -> showPanel(new DoUongPanel()));
        btnQuanLyDon.addActionListener(e -> showPanel(new QuanLyDonPanel()));
        btnKhuyenMai.addActionListener(e -> showPanel(new KhuyenMaiPanel()));
        btnBan.addActionListener(e -> showPanel(new BanPanel()));

        // 🔥 Xử lý đăng xuất
        btnDangXuat.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn đăng xuất?",
                "Đăng xuất",
                JOptionPane.YES_NO_OPTION
            );
            if (confirm == JOptionPane.YES_OPTION) {
                dispose(); // Đóng AdminForm
                new DangNhap().setVisible(true); // Quay về form đăng nhập
            }
        });
    }

    private void styleButton(JButton btn) {
        btn.setBackground(new Color(57, 62, 70));
        btn.setForeground(Color.WHITE);
        btn.setFocusPainted(false);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 16));
    }

    public void showPanel(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
