/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Connect.DBConnection;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.Date;

public class FormTaoDonHang extends JFrame {
    private JTextField txtMaDon, txtMaDonCho, txtTrangThai;
    private JButton btnTao;

    public FormTaoDonHang() {
        setTitle("Tạo đơn hàng mới");
        setSize(300, 250);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new GridLayout(5, 2, 5, 5));

        JLabel lblMaDon = new JLabel("Mã đơn hàng:");
        JLabel lblMaDonCho = new JLabel("Mã đơn chờ:");
        JLabel lblTrangThai = new JLabel("Trạng thái:");

        txtMaDon = new JTextField();
        txtMaDonCho = new JTextField();
        txtTrangThai = new JTextField();
        btnTao = new JButton("Tạo đơn hàng");

        add(lblMaDon); add(txtMaDon);
        add(lblMaDonCho); add(txtMaDonCho);
        add(lblTrangThai); add(txtTrangThai);
        add(new JLabel()); add(btnTao);

        btnTao.addActionListener(e -> themDon());

        setVisible(true);
    }

    private void themDon() {
        try {
            int maDon = Integer.parseInt(txtMaDon.getText());
            int maDonCho = Integer.parseInt(txtMaDonCho.getText());
            String trangThai = txtTrangThai.getText();
            Date now = new Date();

            try (Connection conn = DBConnection.getConnect()) {
                String sql = "INSERT INTO DonHang (MaDonHang, NgayDatHang, MaDonCho, TrangThai) VALUES (?, ?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, maDon);
                pst.setDate(2, new java.sql.Date(now.getTime()));
                pst.setInt(3, maDonCho);
                pst.setString(4, trangThai);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Tạo đơn hàng thành công!");
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
