/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.TaiKhoanDAO;
import dao.NguoiDungDAO;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Admin
 */
public class ResetPasswordForm extends javax.swing.JFrame {

    /**
     * Creates new form ResetPasswordForm
     */
    private JTextField txtEmail, txtHoTen, txtSDT;
    private JPasswordField txtMatKhauMoi;
    private JButton btnDoiMatKhau;

    public ResetPasswordForm() {
        setTitle("NgolDrinks - Reset Password");
        setSize(400, 350);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel(null);
        panel.setBackground(new Color(0, 0, 0, 150));

        JLabel lblEmail = new JLabel("Email:");
        lblEmail.setForeground(Color.WHITE);
        lblEmail.setBounds(50, 30, 100, 25);
        panel.add(lblEmail);

        txtEmail = new JTextField();
        txtEmail.setBounds(160, 30, 180, 25);
        panel.add(txtEmail);

        JLabel lblHoTen = new JLabel("Họ tên:");
        lblHoTen.setForeground(Color.WHITE);
        lblHoTen.setBounds(50, 70, 100, 25);
        panel.add(lblHoTen);

        txtHoTen = new JTextField();
        txtHoTen.setBounds(160, 70, 180, 25);
        panel.add(txtHoTen);

        JLabel lblSDT = new JLabel("Số điện thoại:");
        lblSDT.setForeground(Color.WHITE);
        lblSDT.setBounds(50, 110, 100, 25);
        panel.add(lblSDT);

        txtSDT = new JTextField();
        txtSDT.setBounds(160, 110, 180, 25);
        panel.add(txtSDT);

        JLabel lblMatKhauMoi = new JLabel("Mật khẩu mới:");
        lblMatKhauMoi.setForeground(Color.WHITE);
        lblMatKhauMoi.setBounds(50, 150, 100, 25);
        panel.add(lblMatKhauMoi);

        txtMatKhauMoi = new JPasswordField();
        txtMatKhauMoi.setBounds(160, 150, 180, 25);
        panel.add(txtMatKhauMoi);

        btnDoiMatKhau = new JButton("Đổi mật khẩu");
        btnDoiMatKhau.setBackground(new Color(52, 152, 219));
        btnDoiMatKhau.setForeground(Color.WHITE);
        btnDoiMatKhau.setBounds(110, 200, 180, 30);
        panel.add(btnDoiMatKhau);

        add(panel);

        btnDoiMatKhau.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                doiMatKhau();
            }
        });
    }

    private void doiMatKhau() {
        String email = txtEmail.getText();
        String hoTen = txtHoTen.getText();
        String sdt = txtSDT.getText();
        String matKhauMoi = new String(txtMatKhauMoi.getPassword());

        boolean thongTinDung = NguoiDungDAO.kiemTraThongTin(email, hoTen, sdt);

        if (thongTinDung) {
            TaiKhoanDAO.capNhatMatKhau(email, matKhauMoi);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Thông tin không khớp!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
