/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Connect.DBConnection;

import javax.swing.*;
import java.awt.*;
import java.sql.*;
/**
 *
 * @author Admin
 */
public class ThongTinPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinPanel
     */
    private JTextField txtEmail, txtHoTen, txtNgaySinh, txtSdt, txtDiaChi, txtGioiTinh;
    private String emailDangNhap;

    public ThongTinPanel(String emailDangNhap) {
        this.emailDangNhap = emailDangNhap;

        setLayout(new GridLayout(6, 2, 10, 10));
        setBorder(BorderFactory.createTitledBorder("Thông tin tài khoản"));

        // 🟦 Label và TextField
        add(new JLabel("Email:"));
        txtEmail = createDisabledField();
        add(txtEmail);

        add(new JLabel("Họ tên:"));
        txtHoTen = createDisabledField();
        add(txtHoTen);

        add(new JLabel("Ngày sinh:"));
        txtNgaySinh = createDisabledField();
        add(txtNgaySinh);

        add(new JLabel("Số điện thoại:"));
        txtSdt = createDisabledField();
        add(txtSdt);

        add(new JLabel("Địa chỉ:"));
        txtDiaChi = createDisabledField();
        add(txtDiaChi);

        add(new JLabel("Giới tính:"));
        txtGioiTinh = createDisabledField();
        add(txtGioiTinh);

        // 🟦 Load dữ liệu từ DB
        loadThongTin();
    }

    private JTextField createDisabledField() {
        JTextField field = new JTextField();
        field.setEnabled(false); // ❌ Không cho phép nhập
        field.setDisabledTextColor(Color.BLACK); // Màu chữ khi disabled
        field.setBackground(new Color(230, 230, 230)); // Màu nền nhẹ
        return field;
    }

    private void loadThongTin() {
        try (Connection conn = DBConnection.getConnect()) {
            String sql = """
                SELECT tk.Email, nd.Hoten, nd.NgaySinh, nd.Sdt, nd.DiaChi, nd.GioiTinh
                FROM Taikhoan tk
                JOIN Nguoidung nd ON tk.Manguoidung = nd.Manguoidung
                WHERE tk.Email = ?
            """;
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, emailDangNhap);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                txtEmail.setText(rs.getString("Email"));
                txtHoTen.setText(rs.getString("Hoten"));
                txtNgaySinh.setText(rs.getDate("NgaySinh").toString());
                txtSdt.setText(rs.getString("Sdt"));
                txtDiaChi.setText(rs.getString("DiaChi"));
                txtGioiTinh.setText(rs.getString("GioiTinh"));
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin tài khoản!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi tải thông tin: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
